name: Node App CI
on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main 

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test 
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-content
          path: ./

  release-project:
    runs-on: ubuntu-latest
    needs: ['build-test']
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: server-content
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: Archive site content
        uses: thedoctor0/zip-release@0.7.5
        with:
          filename: web.zip

      - name: Create github release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}